name: Checks
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: brunojppb/actions/setup-pnpm@latest
        with:
          node_version: 16
          pnpm_version: 7

      - name: Checks
        run: pnpm test
